"use strict";

const fs = require("fs");
const path = require("path");
const archiver = require("archiver");
const { STORAGE_ROOT } = require("../../routes/creatorUploads.js");

const README_TEXT = `This is a best-effort CapCut/Jianying-compatible draft, generated by Way AI Code's
Creator Studio. CapCut has never published an official spec for its draft format —
this targets the structure documented by community reverse-engineering projects, not
guaranteed byte-for-byte for every CapCut version.

To use it:
1. Extract this zip directly into your CapCut "Drafts" folder (the same folder CapCut
   itself creates local projects in).
2. Open CapCut. The draft should appear in your project list.
3. If CapCut opens the project but a clip shows as missing/offline, use CapCut's
   "Relink media" action and point it at the corresponding file under this draft's
   materials/video or materials/audio folder.
`;

async function fetchImageBytes(url) {
  if (url.startsWith("data:")) {
    const commaIndex = url.indexOf(",");
    const meta = url.slice(5, commaIndex);
    const base64 = meta.includes("base64");
    const data = url.slice(commaIndex + 1);
    return base64 ? Buffer.from(data, "base64") : Buffer.from(decodeURIComponent(data), "utf8");
  }
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to download scene image (HTTP ${response.status})`);
  return Buffer.from(await response.arrayBuffer());
}

// Audio scenes are always our own uploaded relative storage path (see
// creatorNarrationWorkflow.js's generateSceneVoiceover — it uploads via
// routes/creatorUploads.js and stores the relative path, never a URL), so
// this reads straight off disk rather than making an HTTP round-trip.
function readAudioBytes(relPath) {
  const resolved = path.resolve(path.join(STORAGE_ROOT, relPath));
  const resolvedRoot = path.resolve(STORAGE_ROOT);
  if (!resolved.startsWith(resolvedRoot + path.sep)) {
    throw new Error("Invalid audio path");
  }
  return fs.readFileSync(resolved);
}

/**
 * Streams a CapCut draft zip to `res` (an Express response, already given
 * appropriate headers by the caller). Resolves once the archive is finalized
 * and fully flushed.
 */
async function streamCapCutZip({ draftContent, draftMetaInfo, mediaManifest, draftName }, res) {
  const archive = archiver("zip", { zlib: { level: 9 } });
  const finished = new Promise((resolve, reject) => {
    archive.on("error", reject);
    res.on("finish", resolve);
  });
  archive.pipe(res);

  const root = draftName || "way-ai-creator-export";
  archive.append(JSON.stringify(draftContent, null, 2), { name: `${root}/draft_content.json` });
  archive.append(JSON.stringify(draftMetaInfo, null, 2), { name: `${root}/draft_meta_info.json` });
  archive.append(README_TEXT, { name: `${root}/README.txt` });

  for (const item of mediaManifest) {
    const bytes = item.kind === "audio" ? readAudioBytes(item.url) : await fetchImageBytes(item.url);
    archive.append(bytes, { name: `${root}/${item.relPath}` });
  }

  await archive.finalize();
  await finished;
}

module.exports = { streamCapCutZip };
